# Generated by Django 4.2.4 on 2023-08-20 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ool
import simple_history.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', tinymce.models.HTMLField(max_length=100, verbose_name='Описание')),
                ('role', models.CharField(choices=[('SIMPLE', 'Simple'), ('ADVANCED', 'Advanced')], default='SIMPLE', max_length=100, verbose_name='Роль')),
                ('version', ool.VersionField(default=0)),
            ],
            options={
                'verbose_name': 'TmpModel',
                'verbose_name_plural': 'TmpModels',
            },
            bases=(ool.VersionedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTmpModel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', tinymce.models.HTMLField(max_length=100, verbose_name='Описание')),
                ('role', models.CharField(choices=[('SIMPLE', 'Simple'), ('ADVANCED', 'Advanced')], default='SIMPLE', max_length=100, verbose_name='Роль')),
                ('version', ool.VersionField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical TmpModel',
                'verbose_name_plural': 'historical TmpModels',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
